

services:
  fastapi-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
